# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ecullier <ecullier@student.42perpignan.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/12/23 17:02:53 by ecullier          #+#    #+#              #
#    Updated: 2023/12/23 20:04:58 by ecullier         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=megaphone

CC=g++
CFLAGS=-Wall -Wextra -Werror -g -std=c++98

SRC=megaphone.cpp

OBJ=$(SRC:.cpp=.o)

all : $(NAME)

$(NAME): $(OBJ)
	$(CC) $(OBJ) -o $(NAME)

%.o: %.cpp
	$(CC) -c $(CFLAGS) $< -o $@
clean:
	rm -f $(OBJ)
fclean:
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean